improved curl error reporting

diff --git a/assets/check b/assets/check
--- a/assets/check
+++ b/assets/check
@@ -36,7 +36,7 @@ repository_cert=$(jq -r '.source.repository_cert //empty' < $payload)
 
 # TODO: Add more error checking
 if [ -z "$release_url" ] && [ -z "$snapshot_url" ] ; then
-  echo "[ERROR] invalid payload (must specify url or snapshot_url)"
+  printf '\e[91m[ERROR]\e[0m invalid payload (must specify url)\n'
   exit 1
 fi
 
@@ -71,11 +71,14 @@ else
   metadataUrl="$url/${groupId//.//}/$artifactId/maven-metadata.xml"
 fi
 
-metadata=$(curl --fail --silent --show-error $cert $auth $metadataUrl)
+set +e
+metadata=$(curl --fail --silent --show-error $cert $auth $metadataUrl 2>&1)
 if [ $? -ne 0 ]; then
-  echo "[ERROR] failed to download maven-metadata.xml from: $metadataUrl"
+  printf '\e[91m[ERROR]\e[0m %s\n' "$metadata"
+  printf '\e[91m[ERROR]\e[0m failed to download maven-metadata.xml from: %s\n' "$metadataUrl"
   exit 2
 fi
+set -e
 
 declare -a versions=( )
 if [[ "$version" = *-SNAPSHOT ]]; then
