improved ssl error output and handling for check operation

diff --git a/assets/check b/assets/check
--- a/assets/check
+++ b/assets/check
@@ -32,7 +32,7 @@ repository_cert=$(jq -r '.source.repository_cert //empty' < $payload)
 
 # TODO: Add more error checking
 if [ -z "$release_url" ] && [ -z "$snapshot_url" ] ; then
-  echo "invalid payload (must specify url or snapshot_url)"
+  echo "[ERROR] invalid payload (must specify url or snapshot_url)"
   exit 1
 fi
 
@@ -71,7 +71,11 @@ else
   metadataUrl="$url/${groupId//.//}/$artifactId/maven-metadata.xml"
 fi
 
-metadata=$(curl -s $cert $auth $metadataUrl)
+metadata=$(curl --fail --silent --show-error $cert $auth $metadataUrl)
+if [ $? -ne 0 ]; then
+  echo "[ERROR] failed to download maven-metadata.xml from: $metadataUrl"
+  exit 2
+fi
 
 declare -a versions=( )
 if [[ "$version" = *-SNAPSHOT ]]; then
